### ISSUE TITLE
Ability to disable a project when logged in as admin

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam#73]
When i logged in as admin to Rakam UI, i would like to see an option to disable an already registered project so that users will not be able to see /use it further. This will help us to promote rolling upgrade of projects and ensure we bring down one project and promote a new project for users to adopt.

**Comment by buremba** [comment]
Could you please try `http://RAKAM_URL/current/project/delete` It de-registers the project, removes all reports and dashboard from Rakam UI. If it doesn't solve your problem, feel free to re-open the issue again.

**Comment by sambitdixit** [comment]
Lets say i have two projects. One is events_schema and one is events_sdk. Then i selected events_schema as current project so that every time i logged in it will land in this project. 

If i have to disable the URL will be 

1. http://RAKAM_URL/current/project/delete
2. http://RAKAM_URL/current/events_schema/delete 

Which URL i should use.

**Comment by buremba** [comment]
You should use `http://RAKAM_URL/current/project/delete`. I fixed the error that you found.

**Comment by sambitdixit** [comment]
I tried to disable few projects it still shows up. Since you have access, try disabling projects like "rakam" "rakam-raptor" it does not work. Either i should know if I'm not the owner to disable these the message should be given to me that I'm not the owner and contact "XYZ" who is owner to disable the selected project.
